교육자료/session13/project/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
# /accounts/s
    path('', views.home, name = 'home'),
]

교육자료/session13/project/app/urls.py
from django.urls import path
from app import views
app_name = 'app'
# 중복을 피하기 위한 url 네임스페이스
urlpatterns = [
# /blog/
    path('', views.home, name = 'home'),
    path('new/', views.new, name="new"),
    path('detail/<int:post_pk>/', views.detail, name="detail"),
    path('update/<int:post_pk>/', views.update, name="update"),
    path('delete/<int:post_pk>/', views.delete, name="delete"),
]

교육자료/session13/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
path('admin/', admin.site.urls),
path('blog/', include('app.urls')),
path('accounts/', include('accounts.urls')),
# blog/로 시작되는 url이면, blog하위에 있는 url을 불러온다.
]

교육자료/session13/project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(help_text="User Age",
blank=True, null=True)

교육자료/session13/project/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_posts", null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-create_dt', 'author')



    def __str__(self):
        return f'{self.title}입니다.'
    
    def get_absolute_url(self):
        return reverse(f'blog:post_detail', args=[self.id])
    
    def get_previous(self):
        return self.get_previous_by_create_dt()
    
    def get_next(self):
        return self.get_next_by_create_dt()
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='my_comments')
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_dt', 'post', 'author')
    
    def __str__(self):
        return f'{self.author}-{self.content}'

교육자료/session13/project/accounts/views.py
from django.shortcuts import render
# Create your views here.
def home(request):
    return render(request, 'home.html')

교육자료/session13/project/app/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', {'posts':posts})
def new(request):
    if request.method == "POST":
        new_post = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('detail', new_post.pk)
    return render(request, 'new.html')

def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    return render(request, 'detail.html', {'post':post})
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        Post.objects.filter(pk=post_pk).update(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('detail', post_pk)
    return render(request, 'update.html', {'post':post})
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.delete()
    return redirect('home')

def home(request):
    posts = Post.objects.all()

    return render(request, 'app/home.html', {'posts':posts})

교육자료/session13/project/accounts/templates/home.html
<div>
    <h1>독후감 블로그-회원관리</h1>
    <a href="{% url 'blog:home' %}">독후감 블로그</a>
</div>

교육자료/session13/project/app/templates/app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div><h2>제목</h2>
    <p>{{ post.title }}</p>
    </div>
    <div><h2>내용</h2>
    <p>{{ post.content }}</p>
    </div>
    <a href="{% url 'app:home' %}">홈으로</a>
    <a href="{% url 'app:update' post.pk %}">수정하기</a> <a href="{% url 'app:delete' post.pk %}">삭제하기</a>
    </body>
</html>

교육자료/session13/project/app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>독후감 블로그</h1>
    <div>
        <ul>
            {% for post in posts %}
            <li>
                <a href="{% url 'app:detail' post.pk %}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <a href="{% url 'app:new' %}">글 쓰러가기</a>
</body>
</html>

교육자료/session13/project/app/templates/app/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method = "post">
        {% csrf_token %}
        <div>
            <label for="title">제목</label>
            <input type="text" id="title" name="title" placeholder="제목을 입력해주세요.">
        </div>
        <div>
            <label for="content">내용</label>
            <textarea name="content" id="content" cols="30" rows="10" placeholder="내용을 입력헤주세요."></textarea>
        </div>
        <button type="submit">작성하기</button>
</body>
</html>

교육자료/session13/project/app/templates/app/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
    <div>
        <label for="title">제목</label>
        <input type="text" id="title" name="title" value="{{ post.title }}">
    </div>
    <div>
        <label for="content">내용</label>
        <textarea name="content" id="content" cols="30" rows="10">{{ post.content }}</textarea>
    </div>
    <button type="submit">수정하기</button>
    </form>
</body>
</html>